version: '3.5'

services:
  website:
    build:
      context: './build/apache/.'
      args:
        uid: ${UID}
    container_name: instuyf_apache
    restart: unless-stopped
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    links:
      - db

  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    container_name: instuyf_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_ROOT_HOST: instuyf_mysql
    volumes:
      - ./spuyt-mysql-data:/var/lib/mysql
      - ./build/mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

networks:
  default:
    external:
      name: spuyt
