name: instuyf

on:
  push:
    branches: [ master ]

jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:
    - name: Copy folder content recursively to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: test
        remote: ${{ secrets.HOSTING_REMOTE_PATH }}
        host: ${{ secrets.HOSTING_SSH_HOST }}
        username: ${{ secrets.HOSTING_SSH_USERNAME }}
        privateKey: ${{ secrets.HOSTING_SSH_KEY }}
